### PR TITLE
SagaTester should be able to await a saga run.

### PR DESCRIPTION
**Pull request by peleteiro**
In some cases I would like to await a saga to run, then assert it results. Real example:

```
describe('doLoadPassage', () => {

  test('needs to load a passage', async () => {
    const saga = new SagaTester({})
    saga.start(doLoadPassage, {bibles, book: gen, chapterNumber: 1})
    await saga.waitFor(LOAD_PASSAGE_SUCCESS)
  })

  test('passage already loaded', async () => {
    const saga = new SagaTester({initialState: {readingPassage: {book: gen, passage: new Passage({bibles, book: gen, chapterNumber: 1})}}})
    await saga.run(doLoadPassage, {bibles, book: gen, chapterNumber: 1})
    expect(saga.calledActions.length).toBe(0)
  })

})
```

It returns the task object on `sagaTester.start`. I also added a utility  method, `run`, that returns a promise (`task.done`) so the test looks prettier (instead of `await start(...).done`).   

What do you guy think?

### CODE REVIEW

**Comment by peleteiro** [comment]
Any update on this issue?

**Comment by modosc** [comment]
@peleteiro see also #14

**Comment by modosc** [comment]
@peleteiro i forked here https://github.com/modosc/better-redux-saga-tester and applied my outstanding prs - this should give you the ability to do what you want. if not feel free to open your pr there and i'll be happy to take a look.

**Comment by 3LOK** [comment]
Hi @peleteiro and @modosc,

I'm really really really sorry for not responding earlier. The honest reason is that for some stupid reason (my fault) I'm not listed on receiving notifications about this package, and I don't check regularly for issues (another my bad).

I'll merge your pull request now, and add my self as a listener to this package. I'll understand of course if you prefer to continue with the fork, but I do promise to respond much better now (I'll add myself to receive notifications).

Sorry again,

 - Yoav.

**Comment by modosc** [comment]
hey @3LOK i'd much rather have someone else manage this than fork. i reopened my pr here, thanks!

**Pull request merged**
