### PR TITLE
Add redux-saga@^1.0.0 compatibility

### PR DESCRIPTION
**Pull request by jeremy-deutsch**
Resolves [#57](https://github.com/wix/redux-saga-tester/issues/57#issue-404572606).

As far as I can tell, there were only two breaking changes between redux-saga pre-1.0 and post-1.0 that we needed to accommodate:
* `task.done` was removed, so we need to use `task.toPromise()` instead where applicable.
* We previously checked if options were being passed in by passing in a number to `logger` instead of a function. The `logger` option was removed, and the `channel` option was added, so now we pass in a number for both and check that at least one valid appropriate message was thrown.

To make sure we stay compatible with both "old" and "new" redux-saga, we also now run tests using both.

Getting eyes on this PR would be great, since it seems like a lot of people's redux-saga upgrade is blocked on this not being compatible. @3LOK

### CODE REVIEW

**Comment by brandoncc** [comment]
@3LOK Is there any plan to merge any of these PR's? I really like the concepts used by this package but I can't even try it....

**Comment by lmerotta** [comment]
I hope this gets merged soon ! I asked Wix to do so.

**Comment by bramski** [comment]
I've emailed wix engineering directly on this today as it's blocking one of our projects from upgrading: Please send email to: wixeng@wix.com to contact them to improve maintenance of this project.

**Comment by brandoncc** [comment]
@bramski It sounds like you are already using this library so you are in a different spot than I was, but I ended up using redux-saga-test-plan to achieve the same integration testing and I really like it a lot.

**Comment by jeremy-deutsch** [comment]
Thanks a lot, @InterAI! 👍

**Pull request merged**
